// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentEvents = `-- name: CountRecentEvents :one
SELECT COUNT(*) AS total
FROM events
WHERE created_at >= $1
`

func (q *Queries) CountRecentEvents(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentEvents, createdAt)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countRecentRegionalEvents = `-- name: CountRecentRegionalEvents :one
SELECT COUNT(*) AS total
FROM events_regional
WHERE region = $1
  AND created_at >= $2
`

type CountRecentRegionalEventsParams struct {
	Region    string             `json:"region"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountRecentRegionalEvents(ctx context.Context, arg CountRecentRegionalEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentRegionalEvents, arg.Region, arg.CreatedAt)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const eventRateByRegion = `-- name: EventRateByRegion :many
SELECT
    region,
    COUNT(*) AS count
FROM events
WHERE created_at >= $1
GROUP BY region
ORDER BY count DESC
`

type EventRateByRegionRow struct {
	Region string `json:"region"`
	Count  int64  `json:"count"`
}

func (q *Queries) EventRateByRegion(ctx context.Context, createdAt pgtype.Timestamptz) ([]EventRateByRegionRow, error) {
	rows, err := q.db.Query(ctx, eventRateByRegion, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventRateByRegionRow
	for rows.Next() {
		var i EventRateByRegionRow
		if err := rows.Scan(&i.Region, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (tenant_id, region, event_type, actor, severity, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertEventParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	Region    string      `json:"region"`
	EventType string      `json:"event_type"`
	Actor     string      `json:"actor"`
	Severity  string      `json:"severity"`
	Payload   []byte      `json:"payload"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.TenantID,
		arg.Region,
		arg.EventType,
		arg.Actor,
		arg.Severity,
		arg.Payload,
	)
	return err
}

const insertRegionalEvent = `-- name: InsertRegionalEvent :exec
INSERT INTO events_regional (tenant_id, region, event_type, actor, severity, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRegionalEventParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	Region    string      `json:"region"`
	EventType string      `json:"event_type"`
	Actor     string      `json:"actor"`
	Severity  string      `json:"severity"`
	Payload   []byte      `json:"payload"`
}

func (q *Queries) InsertRegionalEvent(ctx context.Context, arg InsertRegionalEventParams) error {
	_, err := q.db.Exec(ctx, insertRegionalEvent,
		arg.TenantID,
		arg.Region,
		arg.EventType,
		arg.Actor,
		arg.Severity,
		arg.Payload,
	)
	return err
}

const regionalEventRateByType = `-- name: RegionalEventRateByType :many
SELECT
    event_type,
    COUNT(*) AS count
FROM events_regional
WHERE region = $1
  AND created_at >= $2
GROUP BY event_type
ORDER BY count DESC
`

type RegionalEventRateByTypeParams struct {
	Region    string             `json:"region"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RegionalEventRateByTypeRow struct {
	EventType string `json:"event_type"`
	Count     int64  `json:"count"`
}

func (q *Queries) RegionalEventRateByType(ctx context.Context, arg RegionalEventRateByTypeParams) ([]RegionalEventRateByTypeRow, error) {
	rows, err := q.db.Query(ctx, regionalEventRateByType, arg.Region, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegionalEventRateByTypeRow
	for rows.Next() {
		var i RegionalEventRateByTypeRow
		if err := rows.Scan(&i.EventType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
