// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Region    string             `json:"region"`
	EventType string             `json:"event_type"`
	Actor     string             `json:"actor"`
	Severity  string             `json:"severity"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EventCounter struct {
	Target string `json:"target"`
	Cnt    int64  `json:"cnt"`
}

type EventsRegional struct {
	Region    string             `json:"region"`
	ID        uuid.UUID          `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	EventType string             `json:"event_type"`
	Actor     string             `json:"actor"`
	Severity  string             `json:"severity"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID         uuid.UUID          `json:"id"`
	QosTier    string             `json:"qos_tier"`
	HomeRegion string             `json:"home_region"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
