// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAllEvents(ctx context.Context) (int64, error)
	CountAllRegionalEvents(ctx context.Context) (int64, error)
	CountRecentEvents(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	CountRecentRegionalEvents(ctx context.Context, arg CountRecentRegionalEventsParams) (int64, error)
	CountTenantEvents(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountTenants(ctx context.Context) (int64, error)
	CountTenantsByRegion(ctx context.Context) ([]CountTenantsByRegionRow, error)
	EventRateByRegion(ctx context.Context, createdAt pgtype.Timestamptz) ([]EventRateByRegionRow, error)
	EventsPerTenant(ctx context.Context) ([]EventsPerTenantRow, error)
	// Returns per-target write counts from the event_counters table.
	// These are maintained via UPDATE inside each insert transaction —
	// a 4-row primary-key scan, no full table scan required.
	GetCounters(ctx context.Context) ([]EventCounter, error)
	// Increments the counter for one target within the calling transaction.
	IncrementCounter(ctx context.Context, target string) error
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertRegionalEvent(ctx context.Context, arg InsertRegionalEventParams) error
	InsertTenant(ctx context.Context, arg InsertTenantParams) error
	LoadTenants(ctx context.Context) ([]Tenant, error)
	LoadTenantsByRegion(ctx context.Context, homeRegion string) ([]Tenant, error)
	RegionalEventRateByType(ctx context.Context, arg RegionalEventRateByTypeParams) ([]RegionalEventRateByTypeRow, error)
}

var _ Querier = (*Queries)(nil)
