// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAllEvents = `-- name: CountAllEvents :one
SELECT COUNT(*) AS total FROM events
`

func (q *Queries) CountAllEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllEvents)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countAllRegionalEvents = `-- name: CountAllRegionalEvents :one
SELECT COUNT(*) AS total FROM events_regional
`

func (q *Queries) CountAllRegionalEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllRegionalEvents)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countTenantEvents = `-- name: CountTenantEvents :one
SELECT COUNT(*) AS total
FROM events
WHERE tenant_id = $1
`

func (q *Queries) CountTenantEvents(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantEvents, tenantID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countTenants = `-- name: CountTenants :one
SELECT COUNT(*) AS total FROM tenants
`

func (q *Queries) CountTenants(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTenants)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countTenantsByRegion = `-- name: CountTenantsByRegion :many
SELECT home_region, COUNT(*) AS total
FROM tenants
GROUP BY home_region
ORDER BY home_region
`

type CountTenantsByRegionRow struct {
	HomeRegion string `json:"home_region"`
	Total      int64  `json:"total"`
}

func (q *Queries) CountTenantsByRegion(ctx context.Context) ([]CountTenantsByRegionRow, error) {
	rows, err := q.db.Query(ctx, countTenantsByRegion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTenantsByRegionRow
	for rows.Next() {
		var i CountTenantsByRegionRow
		if err := rows.Scan(&i.HomeRegion, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsPerTenant = `-- name: EventsPerTenant :many
SELECT tenant_id, COUNT(*) AS total
FROM events
WHERE tenant_id IS NOT NULL
GROUP BY tenant_id
ORDER BY total DESC
`

type EventsPerTenantRow struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Total    int64       `json:"total"`
}

func (q *Queries) EventsPerTenant(ctx context.Context) ([]EventsPerTenantRow, error) {
	rows, err := q.db.Query(ctx, eventsPerTenant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventsPerTenantRow
	for rows.Next() {
		var i EventsPerTenantRow
		if err := rows.Scan(&i.TenantID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCounters = `-- name: GetCounters :many
SELECT target, cnt FROM event_counters ORDER BY target
`

// Returns per-target write counts from the event_counters table.
// These are maintained via UPDATE inside each insert transaction —
// a 4-row primary-key scan, no full table scan required.
func (q *Queries) GetCounters(ctx context.Context) ([]EventCounter, error) {
	rows, err := q.db.Query(ctx, getCounters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventCounter
	for rows.Next() {
		var i EventCounter
		if err := rows.Scan(&i.Target, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementCounter = `-- name: IncrementCounter :exec
UPDATE event_counters SET cnt = cnt + 1 WHERE target = $1
`

// Increments the counter for one target within the calling transaction.
func (q *Queries) IncrementCounter(ctx context.Context, target string) error {
	_, err := q.db.Exec(ctx, incrementCounter, target)
	return err
}

const insertTenant = `-- name: InsertTenant :exec
INSERT INTO tenants (id, qos_tier, home_region)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type InsertTenantParams struct {
	ID         uuid.UUID `json:"id"`
	QosTier    string    `json:"qos_tier"`
	HomeRegion string    `json:"home_region"`
}

func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) error {
	_, err := q.db.Exec(ctx, insertTenant, arg.ID, arg.QosTier, arg.HomeRegion)
	return err
}

const loadTenants = `-- name: LoadTenants :many
SELECT id, qos_tier, home_region, created_at
FROM tenants
ORDER BY home_region, qos_tier, id
`

func (q *Queries) LoadTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, loadTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.QosTier,
			&i.HomeRegion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadTenantsByRegion = `-- name: LoadTenantsByRegion :many
SELECT id, qos_tier, home_region, created_at
FROM tenants
WHERE home_region = $1
ORDER BY qos_tier, id
`

func (q *Queries) LoadTenantsByRegion(ctx context.Context, homeRegion string) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, loadTenantsByRegion, homeRegion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.QosTier,
			&i.HomeRegion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
